### ISSUE TITLE
bug: NibiJS is broken outside of a browser context.

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/ts-sdk#251]
## How to reproduce
1. `rm -rf node-modules`
2. `nvm use` (to use `.nvmrc`)
3. `yarn install`
4. Go to `examples` with `cd` and try to create a wallet using only `nibijs` as a dependency.

Version used: nibijs v0.21.42  
Commit: 8409d2aaa593784cad440c52de972947b29e7075

## Resulting error:

```
33 | };
34 | Object.defineProperty(exports, "__esModule", { value: true });
35 | exports.chainToParts = exports.isRestEndptLive = exports.queryChainIdWithRest = exports.Devnet = exports.IncentivizedTestent = exports.Localnet = exports.CustomChain = void 0;
36 | const cf = __importStar(require("cross-fetch"));
37 | const types_1 = require("./types");
38 | window.fetch = cf.fetch;
   ^
ReferenceError: Can't find variable: window
      at /home/realu/warpath/NibiruChain/ts-sdk/examples/node_modules/@nibiruchain/nibijs/dist/chain/chain.js:38:0
      at globalThis (/home/realu/warpath/NibiruChain/ts-sdk/examples/node_modules/@nibiruchain/nibijs/dist/chain/chain.js:115:23)
      at overridableRequire (:1:20)
      at /home/realu/warpath/NibiruChain/ts-sdk/examples/node_modules/@nibiruchain/nibijs/dist/chain/index.js:17:0
      at globalThis (/home/realu/warpath/NibiruChain/ts-sdk/examples/node_modules/@nibiruchain/nibijs/dist/chain/index.js:21:44)
      at overridableRequire (:1:20)
      at /home/realu/warpath/NibiruChain/ts-sdk/examples/node_modules/@nibiruchain/nibijs/dist/index.js:17:0
      at globalThis (/home/realu/warpath/NibiruChain/ts-sdk/examples/node_modules/@nibiruchain/nibijs/dist/index.js:23:43)
```

**Comment by Unique-Divine** [comment]
Note: We may want new "reproduce" instructions since the example dir has changed and the library is updated for v0.21.43

**Comment by cgilbe27** [comment]
This is no longer an issue
