### ISSUE TITLE
Example 02 and 03 erroring out

### ISSUE THREAD

**Issue by sbneo2022** [NibiruChain/ts-sdk#62]
**Example 2:** 

ts-node examples/02_queries.ts
/opt/homebrew/lib/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
examples/02_queries.ts:2:10 - error TS2724: '"@nibiruchain/nibijs/dist/query"' has no exported member named 'initQueryCmd'. 

2 import { initQueryCmd } from "@nibiruchain/nibijs/dist/query"
           ~~~~~~~~~~~~

    at createTSError (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 2724 ]
}

**Possible solution : the function name might have changed** 

Example 3:

ts-node examples/03_queries.ts
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module './03_queries.ts'
Require stack:
- /Users/sankhabanerjee/DesktopS/MiscExamples/ts-sdk/examples/imaginaryUncacheableRequireResolveScript
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at requireResolveNonCached (/opt/homebrew/lib/node_modules/ts-node/dist/bin.js:549:16)
    at getProjectSearchDir (/opt/homebrew/lib/node_modules/ts-node/dist/bin.js:519:40)
    at phase3 (/opt/homebrew/lib/node_modules/ts-node/dist/bin.js:267:27)
    at bootstrap (/opt/homebrew/lib/node_modules/ts-node/dist/bin.js:47:30)
    at main (/opt/homebrew/lib/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/sankhabanerjee/DesktopS/MiscExamples/ts-sdk/examples/imaginaryUncacheableRequireResolveScript'
  ]
}

Node.js v18.11.0

**Comment by Unique-Divine** [comment]
It depends which version you're using. The latest version has many updates, so the examples are for any versions compatible with one commented at the top of the file.

**Comment by Unique-Divine** [comment]
This block tells the version number. 

```js
import { Testnet } from "@nibiruchain/nibijs" // nibijs v0.7.3
import { initQueryCmd } from "@nibiruchain/nibijs/dist/query"
```

You can switch versions with 
```bash
yarn add @nibiruchain/nibijs@0.7.3
```
